### ISSUE TITLE
执行java -jar dubbo-admin-0.1.jar报错

### ISSUE THREAD

**Issue by hechunping** [apache/incubator-dubbo-admin#337]
启动dubbo admin报错，提示连接不是zk，部分错误信息如下：
2019-03-20 23:17:11.183 ERROR 13993 --- [           main] org.apache.curator.ConnectionState       : Connection timed out for connection string (127.0.0.1:2181) and timeout (15000) / elapsed (15224)

org.apache.curator.CuratorConnectionLossException: KeeperErrorCode = ConnectionLoss
	at org.apache.curator.ConnectionState.checkTimeouts(ConnectionState.java:225)
	at org.apache.curator.ConnectionState.getZooKeeper(ConnectionState.java:94)
	at org.apache.curator.CuratorZookeeperClient.getZooKeeper(CuratorZookeeperClient.java:117)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.getZooKeeper(CuratorFrameworkImpl.java:489)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:237)
	at org.apache.curator.framework.imps.ExistsBuilderImpl$3.call(ExistsBuilderImpl.java:226)
	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:109)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForegroundStandard(ExistsBuilderImpl.java:223)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.pathInForeground(ExistsBuilderImpl.java:216)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:175)
	at org.apache.curator.framework.imps.ExistsBuilderImpl.forPath(ExistsBuilderImpl.java:32)
	at org.apache.dubbo.admin.registry.config.impl.ZookeeperConfiguration.getConfig(ZookeeperConfiguration.java:109)
	at org.apache.dubbo.admin.registry.config.impl.ZookeeperConfiguration.getConfig(ZookeeperConfiguration.java:75)
	at org.apache.dubbo.admin.config.ConfigCenter.getDynamicConfiguration(ConfigCenter.java:83)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$db2f6419.CGLIB$getDynamicConfiguration$2(<generated>)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$db2f6419$$FastClassBySpringCGLIB$$8ba8b9b3.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at org.apache.dubbo.admin.config.ConfigCenter$$EnhancerBySpringCGLIB$$db2f6419.getDynamicConfiguration(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1254)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1103)
我的配置文件../dubbo-admin-server/src/main/resources/application.properties关于zk（集群）的配置如下
admin.registry.address=zookeeper://10.81.33.17:2181
admin.config-center=zookeeper://172.17.144.104:2181
admin.metadata-report.address=zookeeper://172.17.144.101:2181
请问是我的配置有问题吗？

**Comment by nzomkxia** [comment]
你的配置里面没有127.0.0.1:2181，但是zk尝试去连接，可以看一下配置中心`admin.config-center=zookeeper://172.17.144.104:2181`里面，`/dubbo/config/dubbo/dubbo.properties`有没有这个配置，或者有没有其他配置文件上游127.0.0.1:2181这个地址
