### ISSUE TITLE
关于多注册中心配置的问题

### ISSUE THREAD

**Issue by johnxiaohe** [apache/incubator-dubbo-admin#369]
当我使用在服务端设置多个配置中心一直失败之后，我就换回来单注册中心了
# Dubbo 传输协议与暴露端口
dubbo.protocol.name=dubbo
dubbo.protocol.port=20880

#阿里的zookeeper地址以及开放的端口号
dubbo.registry.protocol=zookeeper

#dubbo.configcenter=47.100.58.201:2182
#dubbo.provider.registries=47.100.58.201:2182,47.100.58.201:2181
dubbo.registry.address=zookeeper://47.100.58.201:2181
#dubbo.metadata-report.address=47.100.58.201:2181
spring.main.allow-bean-definition-overriding=true
# 但是还是会报错
# 连上上面那个地址之后又会多去连接一个127.0.0.1:2181这个zk但是我本地是没有配置这个的就一直报错

2019-04-21 17:46:45.055  INFO 16024 --- [00.58.201:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 47.100.58.201/47.100.58.201:2181, sessionid = 0x1013a5815910039, negotiated timeout = 40000
2019-04-21 17:46:45.055  INFO 16024 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: CONNECTED
2019-04-21 17:46:45.373  INFO 16024 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2019-04-21 17:46:45.374  INFO 16024 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=127.0.0.1:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@3e546734
2019-04-21 17:46:45.378  INFO 16024 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Default schema
2019-04-21 17:46:45.378  INFO 16024 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server 127.0.0.1/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
2019-04-21 17:46:45.433  INFO 16024 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8079 (http) with context path ''
2019-04-21 17:46:45.439  INFO 16024 --- [           main] c.e.d.DubboProviderApplication           : Started DubboProviderApplication in 8.783 seconds (JVM running for 11.025)
2019-04-21 17:46:46.387  WARN 16024 --- [127.0.0.1:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_121]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_121]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.9.jar:3.4.9-1757313]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141) ~[zookeeper-3.4.9.jar:3.4.9-1757313]

**Comment by johnxiaohe** [comment]
# 当我换成多注册地址的时候他会先连第二个2181 然后再连第一个 第一个就怎么都连不上 希望可以帮我看一下谢谢

#阿里的zookeeper地址以及开放的端口号
dubbo.registry.protocol=zookeeper

#dubbo.configcenter=47.100.58.201:2182
dubbo.provider.registries=47.100.58.201:2182,47.100.58.201:2181
#dubbo.registry.address=zookeeper://47.100.58.201:2181
#dubbo.metadata-report.address=47.100.58.201:2181
spring.main.allow-bean-definition-overriding=true

# 错误信息
2019-04-21 17:52:23.375  INFO 2448 --- [00.58.201:2181)] org.apache.zookeeper.ClientCnxn          : Socket connection established to 47.100.58.201/47.100.58.201:2181, initiating session
2019-04-21 17:52:23.480  INFO 2448 --- [00.58.201:2181)] org.apache.zookeeper.ClientCnxn          : Session establishment complete on server 47.100.58.201/47.100.58.201:2181, sessionid = 0x1013a581591003a, negotiated timeout = 40000
2019-04-21 17:52:23.502  INFO 2448 --- [ain-EventThread] o.a.c.f.state.ConnectionStateManager     : State change: CONNECTED
2019-04-21 17:52:55.382  INFO 2448 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2019-04-21 17:52:55.396  INFO 2448 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2019-04-21 17:52:55.411 ERROR 2448 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to subscribe consumer://192.168.32.1/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&connect.timeout=10000&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, cause: Failed to invoke the method subscribe in the service org.apache.dubbo.registry.RegistryService. Tried 3 times of the providers [47.100.58.201:2182] (1/1) from the registry 47.100.58.201:2182 on the consumer 192.168.32.1 using the dubbo version 2.7.0. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://47.100.58.201:2182/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.0.2&group=&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&remote.application=dubbo-provider&remote.timestamp=1555840343751&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2019-04-21 17:52:45.360, end time: 2019-04-21 17:52:55.378, client elapsed: 42 ms, server elapsed: 9976 ms, timeout: 10000 ms, request: Request [id=3, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class org.apache.dubbo.common.URL, interface org.apache.dubbo.registry.NotifyListener], arguments=[consumer://192.168.32.1/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&connect.timeout=10000&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, org.apache.dubbo.registry.integration.RegistryDirectory@5a566922], attachments={path=org.apache.dubbo.registry.RegistryService, sys_callback_arg-1=1515612450, interface=org.apache.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.32.1:0 -> /47.100.58.201:2182
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:306) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:151) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.dubbo.DubboRegistryFactory.createRegistry(DubboRegistryFactory.java:99) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:96) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:278) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:184) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:61) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:106) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:553) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:402) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:345) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:318) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:112) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:58) ~[dubbo-2.7.0.jar:2.7.0]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:896) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:163) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) ~[spring-context-5.1.5.RELEASE.jar:5.1.5.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar:2.1.3.RELEASE]
	at com.example.dubboprovider.DubboProviderApplication.main(DubboProviderApplication.java:13) [classes/:na]
Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke the method subscribe in the service org.apache.dubbo.registry.RegistryService. Tried 3 times of the providers [47.100.58.201:2182] (1/1) from the registry 47.100.58.201:2182 on the consumer 192.168.32.1 using the dubbo version 2.7.0. Last error is: Invoke remote method timeout. method: subscribe, provider: dubbo://47.100.58.201:2182/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&check=false&connect.timeout=10000&dubbo=2.0.2&group=&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&remote.application=dubbo-provider&remote.timestamp=1555840343751&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, cause: Waiting server-side response timeout by scan timer. start time: 2019-04-21 17:52:45.360, end time: 2019-04-21 17:52:55.378, client elapsed: 42 ms, server elapsed: 9976 ms, timeout: 10000 ms, request: Request [id=3, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class org.apache.dubbo.common.URL, interface org.apache.dubbo.registry.NotifyListener], arguments=[consumer://192.168.32.1/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&connect.timeout=10000&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, org.apache.dubbo.registry.integration.RegistryDirectory@5a566922], attachments={path=org.apache.dubbo.registry.RegistryService, sys_callback_arg-1=1515612450, interface=org.apache.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.32.1:0 -> /47.100.58.201:2182
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:111) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:241) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:75) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:57) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.common.bytecode.proxy0.subscribe(proxy0.java) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.dubbo.DubboRegistry.doSubscribe(DubboRegistry.java:152) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:289) ~[dubbo-2.7.0.jar:2.7.0]
	... 32 common frames omitted
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2019-04-21 17:52:45.360, end time: 2019-04-21 17:52:55.378, client elapsed: 42 ms, server elapsed: 9976 ms, timeout: 10000 ms, request: Request [id=3, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=subscribe, parameterTypes=[class org.apache.dubbo.common.URL, interface org.apache.dubbo.registry.NotifyListener], arguments=[consumer://192.168.32.1/org.apache.dubbo.registry.RegistryService?application=dubbo-provider&callbacks=10000&connect.timeout=10000&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&lazy=true&methods=lookup,subscribe,unsubscribe,unregister,register&pid=2448&qos.enable=false&reconnect=false&release=2.7.0&sticky=true&subscribe.1.callback=true&timeout=10000&timestamp=1555840343751&unsubscribe.1.callback=false, org.apache.dubbo.registry.integration.RegistryDirectory@5a566922], attachments={path=org.apache.dubbo.registry.RegistryService, sys_callback_arg-1=1515612450, interface=org.apache.dubbo.registry.RegistryService, version=0.0.0, timeout=10000}]], channel: 192.168.32.1:0 -> /47.100.58.201:2182
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.returnFromResponse(DefaultFuture.java:296) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:191) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.get(DefaultFuture.java:164) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:108) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:156) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:77) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:88) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:49) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:54) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:73) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56) ~[dubbo-2.7.0.jar:2.7.0]
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80) ~[dubbo-2.7.0.jar:2.7.0]
	... 38 common frames omitted

**Comment by johnxiaohe** [comment]
![Uploading image.png…](http://47.100.58.201/img/git.png)

**Comment by johnxiaohe** [comment]
http://47.100.58.201/img/git.png

**Comment by johnxiaohe** [comment]
具体原因位置 修改元数据注册中心位置修改到最上面就不会再去多连接127.0.0.1:2181这个地址了  就算再移回去最下面还不会报错 具体原因未知
